import { REPORT_STYLES } from './report-styles';

export interface StatCard {
  value: string | number;
  label: string;
  color?: string;
}

export interface TableConfig {
  headers: string[];
  rows: string[][];
}

export interface HtmlReportSection {
  title: string;
  content: string;
}

export interface ReportOptions {
  title: string;
  packageName: string;
  packageUrl?: string;
  bugUrl?: string;
  version?: string;
  emoji?: string;
}

/**
 * Generic HTML tag builder to reduce string template noise.
 */
function tag(
  name: string,
  content: string = '',
  attrs: Record<string, string> = {}
): string {
  const attrStr = Object.entries(attrs)
    .map(([k, v]) => ` ${k}="${v}"`)
    .join('');
  return `<${name}${attrStr}>${content}</${name}>`;
}

export function generateReportHead(
  title: string,
  styles: string = REPORT_STYLES
): string {
  return `<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n  ${tag('title', title)}\n  ${tag('style', styles)}\n</head>`;
}

export function generateReportHero(title: string, subtitle?: string): string {
  return tag('div', tag('h1', title) + (subtitle ? tag('p', subtitle) : ''), {
    class: 'hero',
  });
}

export function generateStatCards(cards: StatCard[]): string {
  const cardsHtml = cards
    .map((c) =>
      tag(
        'div',
        tag('div', String(c.value), {
          class: 'stat-value',
          ...(c.color ? { style: `color: ${c.color}` } : {}),
        }) + tag('div', c.label, { class: 'stat-label' }),
        { class: 'stat-card' }
      )
    )
    .join('');
  return tag('div', cardsHtml, { class: 'stats' });
}

export function generateTable(config: TableConfig): string {
  const head = tag(
    'thead',
    tag('tr', config.headers.map((h: string) => tag('th', h)).join(''))
  );
  const body = tag(
    'tbody',
    config.rows
      .map((row: string[]) =>
        tag('tr', row.map((cell) => tag('td', cell)).join(''))
      )
      .join('')
  );
  return tag('table', head + body);
}

export function generateIssueSummary(
  crit: number,
  maj: number,
  min: number,
  savings?: number
): string {
  const details = [
    tag('span', `🔴 Critical: ${crit}`, { class: 'critical' }),
    tag('span', `🟡 Major: ${maj}`, { class: 'major' }),
    tag('span', `🔵 Minor: ${min}`, { class: 'minor' }),
  ].join(' &nbsp; ');

  const savingsHtml = savings
    ? tag(
        'p',
        tag('strong', 'Potential Savings: ') +
          savings.toLocaleString() +
          ' tokens'
      )
    : '';

  return tag(
    'div',
    tag('h2', '⚠️ Issues Summary') + tag('p', details) + savingsHtml,
    { class: 'card', style: 'margin-bottom: 30px;' }
  );
}

export function generateReportFooter(options: ReportOptions): string {
  const version = options.version ? ` v${options.version}` : '';
  const links = [];
  if (options.packageUrl)
    links.push(
      tag(
        'p',
        `Like AIReady? ${tag('a', 'Star us on GitHub', { href: options.packageUrl })}`
      )
    );
  if (options.bugUrl)
    links.push(
      tag(
        'p',
        `Like AIReady? ${tag('a', 'Report it here', { href: options.bugUrl })}`
      )
    );

  return tag(
    'div',
    tag(
      'p',
      `Generated by ${tag('strong', '@aiready/' + options.packageName)}` +
        version
    ) + links.join(''),
    { class: 'footer' }
  );
}

export function wrapInCard(content: string, title?: string): string {
  return tag('div', (title ? tag('h2', title) : '') + content, {
    class: 'card',
  });
}

export function generateCompleteReport(
  options: ReportOptions,
  body: string
): string {
  return (
    generateReportHead(options.title) +
    tag('body', body + generateReportFooter(options))
  );
}

export function generateStandardHtmlReport(
  options: ReportOptions,
  stats: StatCard[],
  sections: HtmlReportSection[],
  score?: { value: number | string; label: string }
): string {
  const hero = generateReportHero(
    `${options.emoji || '🔍'} AIReady ${options.title}`,
    `Generated on ${new Date().toLocaleString()}`
  );

  const scoreCard = score
    ? tag(
        'div',
        tag('div', String(score.value), { class: 'score-value' }) +
          tag('div', score.label, { class: 'score-label' }),
        { class: 'score-card' }
      )
    : '';
  const statsCards = generateStatCards(stats);

  const bodyContent = `
    ${hero}
    ${scoreCard}
    ${statsCards}
    ${sections.map((s) => wrapInCard(s.content, s.title)).join('\n')}
  `;

  return generateCompleteReport(options, bodyContent);
}
